[package]
name = "ben-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "1.0" }
tower = { version = "0.5" }
axum = { version = "0.8.8", features = ["json"] }
