[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]
charts-rs = { version = "0.3.27", features = ["image-encoder"] }
clap = { version = "4.5.54", features = ["derive"] }
colorous = "1.0.16"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
